assignment2/products/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', array('as' => 'home', 'uses' => 'PostController@index'));

//

Route::post('user/login', array('as' => 'user.login', 'uses' => 'UserController@login'));
Route::get('user/logout', array('as' => 'user.logout', 'uses' => 'UserController@logout'));
Route::get('comment/create/{id}', array('as' => 'goat', 'uses' => 'CommentController@create'));
Route::post('user/show', array('as' => 'goat2', 'uses' => 'UserController@show'));

Route::get('post/getAddFriend/{id}', array('as' => 'post.getAddFriend', 'uses' => 'PostController@getAddFriend'));
Route::get('post/getRemoveFriend/{id}', array('as' => 'post.getRemoveFriend', 'uses' => 'PostController@getRemoveFriend'));

//

Route::resource('post', 'PostController');
Route::resource('comment', 'CommentController');
Route::resource('user', 'UserController');

assignment2/products/app/models/Product.php
<?php

class Product extends Eloquent
{
    public static $rules = array(
        'name' => 'required|min:5',
        'price' => 'required'
        );
}

assignment2/products/app/controllers/ProductController.php
<?php

class ProductController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$products = Product::all();
		return View::make('product.index', compact('products'));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		if(!Auth::check())return Redirect::route('product.index');
		return View::make('product.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		//
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$product = Product::find($id);
		return View::make('product.show')->with('product', $product);
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		if(!Auth::check())return Redirect::route('product.index');
		
		$product = Product::find($id);
		return View::make('product.edit', compact('product'));
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		if(!Auth::check())return Redirect::route('product.index');
		
		$product = Product::find($id);
		
		$input = Input::all();
		
		$v = Validator::make($input, Product::$rules);
		
		if ($v->passes())
		{
			$product->name = $input['name'];
			$product->price = $input['price'];
			$product->save();
		
			return Redirect::route('product.show', $product->id);
		}
		else
		{
			return Redirect::action('product.edit', $product->id)->withErrors($v);
		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}


}

assignment2/products/app/views/product/create.blade.php
@extends ('product.layout')

@section ('title')
Create Post
@stop

@section ('content')
{{ Form::open(array('action' => 'PostController@store')) }}
<div class="form-group">
{{ Form::label('title', 'Title: ') }}
{{ Form::text('title') }}
{{ $errors->first('title') }}
</div>
<div class="form-group">
{{ Form::label('message', 'Message: ') }}
{{ Form::text('message') }}
{{ $errors->first('message') }}
</div>
<div class="form-group">
{{ Form::label('Public') }}
{{ Form::radio('type', 'public', true) }}</br>
{{ Form::label('Private') }}
{{ Form::radio('type', 'private') }}</br>
{{ Form::label('Friends') }}
{{ Form::radio('type', 'friends') }}</br>
</div>
<div class="form-group">
{{ Form::submit('Create', array('class' => 'btn btn-success')) }}
</div>
{{ Form::close() }}
@stop

assignment2/products/app/views/product/delete.blade.php
@extends ('product.layout')

@section ('title')
Delete Post
@stop

@section ('content')
{{ Form::open(array('method' => 'DELETE', 'route' => array('post.destroy', $product->id))) }}
{{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
{{ Form::close() }}
@stop

assignment2/products/app/views/product/edit.blade.php
@extends ('product.layout')

@section ('title')
Edit Post
@stop

@section ('content')

<h1>Update Post</h1>

{{ Form::model($post, array('method' => 'PUT', 'route' => array('post.update', $post->id))); }}
<div class="form-group">
{{ Form::label('title', 'Title: ') }}
{{ Form::text('title') }}
{{ $errors->first('title') }}
</div>
<div class="form-group">
{{ Form::label('message', 'Message: ') }}
{{ Form::text('message') }}
{{ $errors->first('message') }}
</div>
<div class="form-group">
{{ Form::label('Public') }}
{{ Form::radio('type', 'public', true) }}</br>
{{ Form::label('Private') }}
{{ Form::radio('type', 'private') }}</br>
{{ Form::label('Friends') }}
{{ Form::radio('type', 'friends') }}</br>
</div>
<div class="form-group">
{{ Form::submit('Edit', array('class' => 'btn btn-info')) }}
</div>
{{ Form::close() }}

@stop

assignment2/products/app/views/product/index.blade.php
@extends('product.layout')

@section('title')

Posts

@stop

@section('head')

<h2>{{ link_to_route('post.create', 'Create a new post') }}</h2>
<h2>{{ link_to_route('user.index', 'Search for Users') }}</h2>

@if (Auth::check())
<h2>{{ link_to_route('user.edit', 'Edit user account information', array($user->id)) }}</h2>
@endif

<h1 class="subheader">Friends</h1>
  <table style="width:100%;">
    <thead>
      <tr>
        <th>Full Name: </th>
        <th>Email: </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @if (Auth::check())
      @foreach (Auth::user()->friends as $friend)
      <tr>
          <td>{{ $friend->fullName }}</td>
          <td>{{ $friend->email }}</td>
          <td>{{ link_to_action('PostController@getRemoveFriend', 'Remove friend', array('id' => $friend->id)) }}</td>
      </tr>
      @endforeach
      @else
      @endif
    </tbody>
  </table>

@stop

@section('content')

<h1>Posts</h1>

<ul class ="nav navbar-center">
    
{{-- <img src="{{ asset($user->image->url('thumb')) }}"> --}}
    
@foreach($posts as $post)

@if (!Auth::check())

@if ($post->type == 'public')

<li><h4>{{{ $post->username }}}</h4>{{ link_to_route('post.show', $post->title, array($post->id)) }} {{{ $post->message }}}... </br> This post is {{{ $post->type }}} </br></br> </li>
<li>Please log in to comment...</li></br>

@endif {{-- public --}}

@else {{-- logged in --}}

@if ($post->type == 'private' || 'public' || 'friends')

<li><h4>{{{ $post->username }}}</h4>{{ link_to_route('post.show', $post->title, array($post->id)) }} {{{ $post->message }}}... </br> This post is {{{ $post->type }}} </br></br> </li>
<li>{{ link_to_route('goat', 'Comment', array($post->id, $user->id)) }}</li>

@endif {{-- public, private --}}

@endif {{-- auth --}}

@endforeach

{{ $posts->links() }}

</ul>

@stop

@section('bottom')

<h2 class="subheader">Other People</h2>
  <table style="width:100%;">
    <thead>
      <tr>
        <th>Full name: </th>
        <th>Email: </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @if (Auth::check())
      @foreach ($not_friends as $friend)
      <tr>
          <td>{{ $friend->getFullName() }}</td>
          <td>{{ $friend->email }}</td>
          <td>{{ link_to_action('PostController@getAddFriend', 'Add friend', array('id' => $friend->id)) }}</td>
      </tr>
      @endforeach
      @else
      @endif
    </tbody>
  </table>

@stop

assignment2/products/app/views/product/layout.blade.php
<html>
  <head>
    <title>
        
        @yield('title')
        
    </title>

     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"> 

     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
     
     {{ HTML::style( asset('css/main.css') ) }}

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <h2>Night Chat</h2>
          
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li class="active"><a href="#">Create Post</a></li>
                <li><a href="#">Edit Account</a></li>
                <li><a href="#">Search Users</a></li>
              </ul>
            </div>
        </div>
      </div>
    </nav>
    
    <div id="content" class="col-md-4">

    @if (Auth::check())
      {{ Session::forget('login_error') }}
      <img src="{{asset(Auth::user()->image->url('medium')) }}">
      <h6>{{ Auth::user()->email }} is logged in.</h6> </br>
      <h6>{{ Auth::user()->fullName }}</h6> </br>
      {{ link_to_route('user.logout', 'Logout') }}
      </br></br>
    @else
      {{ link_to_route('user.create', 'Create an Account') }}
      </br></br>
        @if (Session::has('login_error'))
          Login failed!
        @endif
      {{ Form::open(array('url'=> secure_url('user/login'))) }}
      <div class="form-group">
      {{ Form::label('email', 'Email: ') }}
      {{ Form::text('email') }}
      {{ $errors->first('email') }}
      </div>
      <div class="form-group">
      {{ Form::label('password', 'Password: ') }}
      {{ Form::text('password') }}
      {{ $errors->first('password') }}
      </div>
      <div class="form-group">
      {{ Form::submit('Login') }}
      </div>
      {{ Form::close() }}
    @endif
    
    
    
    @yield('head')
    
    </div>
    
  </head>
  
  <body>
    
    <div id="content" class="col-md-5">
      
            @yield('content')
            
    </div>
    
  </body>
  
  <footer>
    
    <div id="content" class="col-md-3">
      
            @yield('bottom')
    
  </footer>
  
</html>

assignment2/products/app/views/product/show.blade.php
@extends('product.layout')

@section('title')
Post (single)
@stop

@section('content')

<h1>Post</h1>

<p>Title: {{{ $post->title }}}</p>
<p>Message: {{{ $post->message }}}</p>

@foreach($comments as $comment)

@if (!Auth::check())

@if ($comment->post_id == $post->id)

<p>Comments: {{ $comment->comment }}</p>

@endif {{-- id against id --}}

@else {{-- auth --}}

@if ($comment->post_id == $post->id)

<p>Comments: {{ $comment->comment }}

@if ($comment->comment_username == Auth::user()->email)

{{ link_to_route('comment.show', 'Delete comment', array($comment->id)) }}</p>

@endif {{-- id against id --}}

@endif {{-- user against email --}}

@endif {{-- auth --}}

@endforeach

{{ $comments->links() }}

<p>{{ link_to_route('post.edit', 'Edit', array($post->id)) }}</p>

@if (Auth::check())

@if ($post->user_id == Auth::user()->id)

{{ Form::open(array('method' => 'DELETE', 'route' => array('post.destroy', $post->id))) }}
{{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
{{ Form::close() }}

@endif {{-- --}}

@else

@endif

@stop